USE [master]
ALTER DATABASE [BowlingLeagueEx] SET SINGLE_USER WITH ROLLBACK IMMEDIATE
BACKUP LOG [BowlingLeagueEx] TO  DISK = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER4\MSSQL\Backup\BowlingLeagueEx.bak' WITH NOFORMAT, NOINIT,  NAME = N'BowlingLeagueEx', NOSKIP, NOREWIND, NOUNLOAD,  NORECOVERY ,  STATS = 5
RESTORE DATABASE [BowlingLeagueEx] FROM  DISK = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER4\MSSQL\Backup\BowlingLeagueEx.bak' WITH  FILE = 1,  NOUNLOAD,  REPLACE,  STATS = 5
ALTER DATABASE [BowlingLeagueEx] SET MULTI_USER

GO

